import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import { Toaster } from "@/components/ui/sonner";
import { RealtimeQuerySync } from "@/components/RealtimeQuerySync";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";

function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold">404</h1><h2 className="mt-4 text-xl font-semibold">Page introuvable</h2><div className="mt-6"><Link to="/" className="inline-flex rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Accueil</Link></div></div></div>}
function errorText(error:unknown){if(error instanceof Response)return `Response ${error.status}${error.statusText?` ${error.statusText}`:""}`;if(error instanceof Error)return error.message||error.name;return String(error??"Erreur inconnue")}
function isChunkLoadError(error:unknown){return /dynamically imported module|module script|failed to fetch|load failed|chunk/i.test(errorText(error))}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){
  console.error(error);const router=useRouter();const message=errorText(error);
  useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"});if(!isChunkLoadError(error)||typeof window==="undefined")return;const key=`icc-route-reload:${window.location.pathname}`;try{if(window.sessionStorage.getItem(key)==="1")return;window.sessionStorage.setItem(key,"1")}catch{}const url=new URL(window.location.href);url.searchParams.set("icc_refresh",Date.now().toString());window.location.replace(url.toString())},[error]);
  return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="w-full max-w-md text-center"><h1 className="text-xl font-semibold tracking-tight">Cette page n’a pas pu charger</h1><p className="mt-2 text-sm text-muted-foreground">Le détail technique ci-dessous permet maintenant d’identifier précisément la cause si le problème persiste.</p><div className="mt-4 break-words rounded-lg border bg-muted/40 p-3 text-left font-mono text-xs" data-testid="route-error-detail">{message}</div><div className="mt-6 flex flex-wrap justify-center gap-2"><button onClick={()=>{router.invalidate();reset()}} className="inline-flex rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Réessayer</button><Link to="/" className="inline-flex rounded-md border border-input bg-background px-4 py-2 text-sm font-medium">Accueil</Link></div></div></div>;
}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{name:"theme-color",content:"#4c0884"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"default"},{name:"apple-mobile-web-app-title",content:"COM ICC Le Mans"},{title:"COM ICC Le Mans — Espace du pôle Communication"},{name:"description",content:"Espace de pilotage du pôle Communication ICC Le Mans : planning, programmes, affectations et sollicitations."}],links:[{rel:"stylesheet",href:appCss},{rel:"icon",href:"/com-icc-lemans/app-icon.svg",type:"image/svg+xml"},{rel:"apple-touch-icon",href:"/com-icc-lemans/app-icon.svg"},{rel:"manifest",href:"/com-icc-lemans/manifest.webmanifest"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="fr"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const{queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><RealtimeQuerySync/><Outlet/><Toaster position="top-center" richColors/></QueryClientProvider>}
