import { Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, CheckCircle2, GraduationCap, Target } from "lucide-react";

import { useCurrentRole } from "@/hooks/useAuth";
import { evaluationsQuery, programsQuery, solicitationsQuery, tasksQuery } from "@/lib/icc";
import { dateInPeriod, rangesOverlap, type DashboardPeriod } from "@/lib/period";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";

function deadlineLabel(date?:string|null){if(!date)return"Sans échéance";const today=new Date();today.setHours(0,0,0,0);const d=new Date(`${date}T00:00:00`),days=Math.ceil((d.getTime()-today.getTime())/86400000);if(days<0)return`En retard de ${Math.abs(days)} j`;if(days===0)return"À répondre aujourd’hui";return`Avant le ${d.toLocaleDateString("fr-FR")}`}
const db=()=>supabase as any;
export function HomeDashboard({period}:{period:DashboardPeriod}){
 const{member,userId}=useCurrentRole();const memberId=member?.id??null;const programs=useQuery(programsQuery),solicitations=useQuery(solicitationsQuery),tasks=useQuery(tasksQuery),evaluations=useQuery(evaluationsQuery);
 const recipients=useQuery({queryKey:["home-solicitation-recipients",memberId],enabled:!!memberId,queryFn:async()=>{const{data,error}=await db().from("solicitation_recipients").select("*").eq("member_id",memberId);if(error)throw error;return data??[]}});
 const memberPaths=useQuery({queryKey:["home-my-training",memberId],enabled:!!memberId,queryFn:async()=>{const{data,error}=await db().from("member_training_paths").select("*").eq("member_id",memberId).is("deleted_at",null);if(error)throw error;return data??[]}});
 const paths=useQuery({queryKey:["home-training-paths"],queryFn:async()=>{const{data,error}=await db().from("training_paths").select("id,name,path_kind,archived");if(error)throw error;return data??[]}});
 const objectives=useQuery({queryKey:["home-my-objectives",memberId],enabled:!!memberId,queryFn:async()=>{const{data,error}=await db().from("evaluation_objectives").select("*").eq("subject_member_id",memberId).order("created_at",{ascending:false});if(error)throw error;return data??[]}});
 const today=new Date().toISOString().slice(0,10),mine=memberId?(programs.data??[]).filter(p=>!p.archived&&p.status!=="cancelled"&&p.assignments.some(a=>a.memberIds.includes(memberId))):[],upcoming=mine.filter(p=>(p.start_date??"9999")>=today&&rangesOverlap(p.start_date,p.end_date,period));
 const periodProgramIds=new Set((programs.data??[]).filter(p=>rangesOverlap(p.start_date,p.end_date,period)).map(p=>p.id));const recipientMap=new Map((recipients.data??[]).map((r:any)=>[r.solicitation_id,r]));const toAnswer=(solicitations.data??[]).filter((s:any)=>!s.archived&&!s.deleted&&s.status!=="cancelled"&&recipientMap.get(s.id)?.response==="pending"&&dateInPeriod(s.event_date??s.response_deadline,period));
 const programResponses=upcoming.filter(p=>!p.responses.some(r=>r.member_id===memberId&&r.status!=="pending"));const myTasks=(tasks.data??[]).filter((t:any)=>t.status!=="done"&&t.assignee_member_id===memberId&&(t.program_id?periodProgramIds.has(t.program_id):dateInPeriod(t.due_date,period)));const myDraftEvals=(evaluations.data??[]).filter((e:any)=>e.status==="draft"&&e.evaluator_user_id===userId&&dateInPeriod(e.created_at,period));
 const actionCount=toAnswer.length+programResponses.length+myTasks.length+myDraftEvals.length;
 const pathMap=new Map((paths.data??[]).map((p:any)=>[p.id,p]));const activeTraining=(memberPaths.data??[]).filter((x:any)=>x.status!=="completed"&&!x.deleted_at&&pathMap.has(x.path_id)&&!(pathMap.get(x.path_id) as any)?.archived);const activeObjectives=(objectives.data??[]).filter((o:any)=>o.status!=="done"&&o.status!=="cancelled");const lastEval=(evaluations.data??[]).find((e:any)=>e.subject_member_id===memberId&&e.status==="validated"&&dateInPeriod(e.created_at,period));
 const cards=[{icon:<CalendarDays className="size-5"/>,value:upcoming.length,label:"Mes services sur la période",to:"/mon-planning"},{icon:<CheckCircle2 className="size-5"/>,value:actionCount,label:"Mes actions sur la période",to:"/a-faire"},{icon:<GraduationCap className="size-5"/>,value:activeTraining.length,label:"Mes formations en cours",to:"/formations"},{icon:<Target className="size-5"/>,value:activeObjectives.length,label:"Mes objectifs en cours",to:"/evaluations"}];
 return <section className="mt-6 rounded-3xl border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-icc-violet">Mon tableau de bord</h2><p className="text-xs text-muted-foreground">Mes chiffres réels. Les éléments datés suivent la période sélectionnée ; formations et objectifs restent des états en cours.</p></div><Link to="/mon-planning" className="rounded-lg bg-icc-violet px-3 py-2 text-xs font-bold text-white hover:bg-icc-violet-hover">📅 Mon planning · Calendrier / Liste</Link></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(c=><Link key={c.label} to={c.to as any} className="rounded-2xl border p-4 transition-colors hover:border-icc-violet/40"><span className="text-icc-violet">{c.icon}</span><b className="mt-1 block text-2xl text-icc-violet">{c.value}</b><small className="text-muted-foreground">{c.label}</small></Link>)}</div>
 <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div><h3 className="font-black text-icc-violet">À faire pour moi</h3><p className="text-xs text-muted-foreground">Uniquement les éléments qui attendent mon action sur la période.</p></div><Link to="/a-faire" className="text-xs font-bold text-icc-violet">Tout voir →</Link></div><div className="mt-3 space-y-2">{toAnswer.slice(0,2).map((s:any)=><Link key={s.id} to="/sollicitations" className="block rounded-xl bg-muted/40 p-3 text-sm"><div className="flex justify-between gap-2"><b>Répondre · {s.event_name||"Sollicitation"}</b><span className="text-xs text-muted-foreground">{deadlineLabel(s.response_deadline)}</span></div></Link>)}{programResponses.slice(0,2).map((p:any)=><Link key={p.id} to="/programme/$id" params={{id:p.id}} className="block rounded-xl bg-muted/40 p-3 text-sm"><b>Confirmer · {p.title}</b></Link>)}{!actionCount?<p className="rounded-xl bg-muted/30 p-3 text-xs text-muted-foreground">Tout est à jour sur cette période.</p>:null}</div></div>
 <div className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div><h3 className="font-black text-icc-violet">Ma progression</h3><p className="text-xs text-muted-foreground">Formations, objectifs et dernière évaluation validée sur la période.</p></div><Link to="/formations" className="text-xs font-bold text-icc-violet">Mes formations →</Link></div><div className="mt-3 space-y-2">{activeTraining.slice(0,2).map((mp:any)=>{const p:any=pathMap.get(mp.path_id);return <div key={mp.id} className="rounded-xl bg-muted/40 p-3 text-sm"><b>{p?.name??"Formation"}</b><p className="text-xs text-muted-foreground">{p?.path_kind==="internal"?"Compétence en acquisition":"Parcours d’intégration"}</p></div>})}{activeObjectives.slice(0,2).map((o:any)=><div key={o.id} className="rounded-xl bg-muted/40 p-3 text-sm"><b>Objectif · {o.label}</b><p className="text-xs text-muted-foreground">{o.due_date?`Échéance ${new Date(`${o.due_date}T12:00:00`).toLocaleDateString("fr-FR")}`:"Sans échéance"}</p></div>)}{lastEval?<Link to="/evaluations" className="block rounded-xl bg-muted/40 p-3 text-sm"><div className="flex items-center gap-2"><b>Dernière évaluation validée</b><Badge variant="outline">{lastEval.period_label??"Voir"}</Badge></div></Link>:null}{!activeTraining.length&&!activeObjectives.length&&!lastEval?<p className="rounded-xl bg-muted/30 p-3 text-xs text-muted-foreground">Aucun élément de progression pour le moment.</p>:null}</div></div></div>
 </section>
}