import { Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { AlertTriangle, Boxes, CalendarDays, ClipboardCheck, GraduationCap, MessageSquareWarning, Users, Wrench } from "lucide-react";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { availabilityQuery, debriefsQuery, evaluationsQuery, membersQuery, polesQuery, programsQuery } from "@/lib/icc";
import { dateInPeriod, rangesOverlap, type DashboardPeriod } from "@/lib/period";
const db=()=>supabase as any;
function perm(uid:string|undefined){return useQuery({queryKey:["org-dashboard-scope",uid],enabled:!!uid,queryFn:async()=>{const tries=[["programmes","consulter"],["membres","consulter"],["pilotage","consulter"]];for(const[p_module,p_action]of tries){const{data}=await db().rpc("access_scope_for_user",{p_user:uid,p_module,p_action});if(data&&data!=="interdit")return data as string}return"interdit"}})}
export function OrganizationDashboard({period}:{period:DashboardPeriod}){
 const{member,userId,isTechAdmin}=useCurrentRole(),scope=perm(userId),programs=useQuery(programsQuery),members=useQuery(membersQuery),poles=useQuery(polesQuery),av=useQuery(availabilityQuery),debriefs=useQuery(debriefsQuery),evals=useQuery(evaluationsQuery),[view,setView]=useState<string>("auto");
 const training=useQuery({queryKey:["org-training"],queryFn:async()=>{const{data,error}=await db().from("member_training_paths").select("id,member_id,path_id,status,deleted_at").is("deleted_at",null);if(error)throw error;return data??[]}});
 const trainingPaths=useQuery({queryKey:["org-training-paths"],queryFn:async()=>{const{data,error}=await db().from("training_paths").select("id,archived").eq("archived",false);if(error)throw error;return data??[]}});
 const team=useQuery({queryKey:["org-teamlife"],queryFn:async()=>{const{data,error}=await db().from("team_life_events").select("id,title,starts_at,status,audience_kind,audience_pole_ids").in("status",["scheduled","postponed"]).is("deleted_at",null);if(error)throw error;return data??[]},retry:false});
 const materialItems=useQuery({queryKey:["org-material-items"],queryFn:async()=>{const{data,error}=await db().from("material_items").select("id,state,primary_pole_id,archived").eq("archived",false);if(error)throw error;return data??[]},retry:false});
 const materialNeeds=useQuery({queryKey:["org-material-needs"],queryFn:async()=>{const{data,error}=await db().from("material_needs").select("id,pole_id,priority,status,estimated_budget");if(error)throw error;return data??[]},retry:false});
 const raw=isTechAdmin?"tous":scope.data;if(!raw||raw==="interdit"||raw==="moi")return null;
 const myPoleIds=(members.data?.links??[]).filter((l:any)=>l.member_id===member?.id).map((l:any)=>l.pole_id),canAll=isTechAdmin||["tous","all"].includes(raw),effective=view==="auto"?(canAll?"all":myPoleIds.length>1?"mine":myPoleIds[0]?`pole:${myPoleIds[0]}`:"mine"):view;
 const activePoleIds=effective==="all"?null:effective==="mine"?myPoleIds:effective.startsWith("pole:")?[effective.slice(5)]:myPoleIds;
 const inScope=(poleId:string|null|undefined)=>activePoleIds===null||!!poleId&&activePoleIds.includes(poleId),scopeLabel=effective==="all"?"Toute la COM":effective==="mine"?"Tous mes pôles":poles.data?.find((p:any)=>p.id===effective.slice(5))?.name??"Mon pôle";
 const scopedPrograms=(programs.data??[]).filter(p=>!p.archived&&p.status!=="cancelled"&&rangesOverlap(p.start_date,p.end_date,period)&&p.assignments.some(a=>inScope(a.pole_id)));const today=new Date().toISOString().slice(0,10),up=scopedPrograms.filter(p=>(p.start_date??"9999")>=today);let needs=0;const pendingKeys=new Set<string>();for(const p of up)for(const a of p.assignments.filter(x=>inScope(x.pole_id))){needs+=Math.max(0,Number(a.required_count??0)-a.memberIds.length);for(const id of a.memberIds)if(!p.responses.some(r=>r.member_id===id&&r.status!=="pending"))pendingKeys.add(`${p.id}:${id}`)}const pending=pendingKeys.size;
 const activeMembers=(members.data?.members??[]).filter((m:any)=>m.status==="active");const activeMemberIds=new Set(activeMembers.map((m:any)=>m.id));const scopedMemberIds=new Set((members.data?.links??[]).filter((l:any)=>inScope(l.pole_id)&&activeMemberIds.has(l.member_id)).map((l:any)=>l.member_id));const pendingAvail=(av.data??[]).filter((x:any)=>x.status==="pending"&&scopedMemberIds.has(x.member_id)&&dateInPeriod(x.starts_at,period)).length;const finished=scopedPrograms.filter(p=>p.start_date&&p.start_date<today),debriefIds=new Set((debriefs.data??[]).filter((d:any)=>dateInPeriod(d.created_at,period)).map((d:any)=>d.program_id)),missingDebrief=finished.filter(p=>!debriefIds.has(p.id)).length;const evalPending=(evals.data??[]).filter((e:any)=>["submitted","revision_requested"].includes(e.status)&&scopedMemberIds.has(e.subject_member_id)&&dateInPeriod(e.created_at,period)).length;const validPathIds=new Set((trainingPaths.data??[]).map((p:any)=>p.id));const trainingMemberIds=new Set((training.data??[]).filter((x:any)=>x.status!=="completed"&&validPathIds.has(x.path_id)&&scopedMemberIds.has(x.member_id)).map((x:any)=>x.member_id));const trainingActive=trainingMemberIds.size;const teamUpcoming=(team.data??[]).filter((e:any)=>e.starts_at&&e.starts_at>=new Date().toISOString()&&dateInPeriod(e.starts_at,period)&&(e.audience_kind==="team"||(e.audience_pole_ids??[]).some((id:string)=>activePoleIds===null||activePoleIds.includes(id)))).length;
 const matRepair=(materialItems.data??[]).filter((x:any)=>inScope(x.primary_pole_id)&&["a_reparer","hors_service"].includes(x.state)).length;
 const matOpen=(materialNeeds.data??[]).filter((x:any)=>inScope(x.pole_id)&&!["recu","refuse"].includes(x.status));const matCritical=matOpen.filter((x:any)=>x.priority==="critique").length;
 const cards=[{n:needs,l:"Besoins non couverts",to:"/programmes",icon:AlertTriangle},{n:pending,l:"Confirmations attendues",to:"/programmes",icon:ClipboardCheck},{n:pendingAvail,l:"Indisponibilités à traiter",to:"/disponibilites",icon:CalendarDays},{n:missingDebrief,l:"Post-services manquants",to:"/post-service",icon:MessageSquareWarning},{n:evalPending,l:"Évaluations à traiter",to:"/evaluations",icon:Users},{n:trainingActive,l:"Personnes en formation",to:"/formations",icon:GraduationCap},{n:matRepair,l:"Matériel à réparer / HS",to:"/materiel-com",icon:Wrench},{n:matCritical,l:"Besoins matériel critiques",to:"/materiel-com",icon:Boxes}];
 return <section className="mt-6 rounded-3xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black text-icc-violet">Vue organisation</h2><p className="text-xs text-muted-foreground">Pilotage réel de {scopeLabel.toLowerCase()}. Les éléments datés suivent la période sélectionnée ; les états courants restent visibles.</p></div><div className="flex flex-wrap gap-2">{canAll?<button onClick={()=>setView("all")} className={`rounded-full border px-3 py-1 text-xs font-bold ${effective==="all"?"bg-icc-violet text-white":"bg-muted"}`}>Toute la COM</button>:null}{myPoleIds.length>1?<button onClick={()=>setView("mine")} className={`rounded-full border px-3 py-1 text-xs font-bold ${effective==="mine"?"bg-icc-violet text-white":"bg-muted"}`}>Tous mes pôles</button>:null}{myPoleIds.map((id:string)=>{const name=poles.data?.find((p:any)=>p.id===id)?.name??"Pôle";return <button key={id} onClick={()=>setView(`pole:${id}`)} className={`rounded-full border px-3 py-1 text-xs font-bold ${effective===`pole:${id}`?"bg-icc-violet text-white":"bg-muted"}`}>{name}</button>})}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(c=><Link key={c.l} to={c.to as any} className="rounded-2xl border p-4 hover:border-icc-violet/40"><c.icon className="size-5 text-icc-violet"/><b className="mt-1 block text-2xl text-icc-violet">{c.n}</b><small className="text-muted-foreground">{c.l}</small></Link>)}</div><div className="mt-4 grid gap-3 md:grid-cols-4"><Link to="/programmes" className="rounded-2xl bg-muted/35 p-4 transition hover:bg-muted/60"><b className="text-xl text-icc-violet">{up.length}</b><p className="text-xs">Programmes à venir sur la période</p></Link><Link to="/poles" className="rounded-2xl bg-muted/35 p-4 transition hover:bg-muted/60"><b className="text-xl text-icc-violet">{scopedMemberIds.size}</b><p className="text-xs">Membres actifs dans le périmètre</p></Link><Link to="/vie-equipe" className="rounded-2xl bg-muted/35 p-4 transition hover:bg-muted/60"><b className="text-xl text-icc-violet">{teamUpcoming}</b><p className="text-xs">Communions fraternelles sur la période</p></Link><Link to="/materiel-com" className="rounded-2xl bg-muted/35 p-4 transition hover:bg-muted/60"><b className="text-xl text-icc-violet">{matOpen.length}</b><p className="text-xs">Besoins matériel ouverts</p></Link></div></section>
}