import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Download, Eye } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/AppShell";
import { useCurrentRole } from "@/hooks/useAuth";
import { downloadExcel, exportStamp, toExcelWorkbook, type Column } from "@/lib/exports";
import { auditQuery, formatDateTime, logAction, membersQuery, polesQuery, programsQuery, solicitationsQuery, tasksQuery } from "@/lib/icc";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
export const Route=createFileRoute("/_authenticated/exports")({head:()=>({meta:[{title:"Exports — COM ICC Le Mans"}]}),component:Exports});const db=()=>supabase as any;
function Exports(){const{member,isStaff,isAdmin,isTechAdmin}=useCurrentRole();const canExport=isStaff||isAdmin||isTechAdmin,preview=!canExport;const poles=useQuery(polesQuery),members=useQuery(membersQuery),programs=useQuery(programsQuery),solicitations=useQuery(solicitationsQuery),tasks=useQuery(tasksQuery),audit=useQuery({...auditQuery,enabled:canExport});const material=useQuery({queryKey:["exports-material"],enabled:canExport,queryFn:async()=>{const[items,needs,requests]=await Promise.all([db().from("material_items").select("*"),db().from("material_needs").select("*"),db().from("material_requests").select("*")]);for(const r of[items,needs,requests])if(r.error)throw r.error;return{items:items.data??[],needs:needs.data??[],requests:requests.data??[]}}});
async function run<T>(name:string,label:string,rows:T[],columns:Column<T>[]){if(!canExport){toast.info("Export réservé");return}if(!rows.length){toast.info("Rien à exporter");return}downloadExcel(`icc-${name}-${exportStamp()}.xls`,toExcelWorkbook(`COM ICC Le Mans — ${label}`,rows,columns));toast.success(`${label} exporté dans Excel`);await logAction({action:"export_excel",entity:name,detail:`${label} — ${rows.length} ligne(s)`,actorName:member?.full_name})}const simple=(name:string,label:string,description:string,rows:any[],cols:Column<any>[])=>({name,label,description,count:rows.length,go:()=>run(name,label,rows,cols)});
const blocks=[simple("equipiers","Équipiers","Identité, rôle, statut et informations d’intégration.",members.data?.members??[],[{key:"full_name",label:"Nom",value:x=>x.full_name},{key:"base_role",label:"Rôle",value:x=>x.base_role},{key:"status",label:"Statut",value:x=>x.status}]),simple("poles","Pôles","Structure des pôles et organisation.",poles.data??[],[{key:"name",label:"Pôle",value:x=>x.name},{key:"description",label:"Description",value:x=>x.description},{key:"archived",label:"Archivé",value:x=>x.archived}]),simple("programmes","Programmes","Dates, statut, lieu et organisation des programmes.",programs.data??[],[{key:"title",label:"Programme",value:x=>x.title},{key:"start_date",label:"Date",value:x=>x.start_date},{key:"status",label:"Statut",value:x=>x.status},{key:"location",label:"Lieu",value:x=>x.location}]),simple("sollicitations","Demandes ponctuelles","Renforts, remplacements, statut et suivi.",solicitations.data??[],[{key:"event_name",label:"Événement",value:x=>x.event_name},{key:"event_date",label:"Date",value:x=>x.event_date},{key:"status",label:"Statut",value:x=>x.status}]),simple("taches","Tâches","Échéances, priorités et état des tâches.",tasks.data??[],[{key:"title",label:"Tâche",value:x=>x.title},{key:"status",label:"Statut",value:x=>x.status==="done"?"Terminée":"À faire"},{key:"priority",label:"Priorité",value:x=>x.priority},{key:"due_date",label:"Échéance",value:x=>x.due_date}]),simple("materiel-inventaire","Matériel COM — Inventaire","Équipements, quantité, état, rangement et valeur.",material.data?.items??[],[{key:"name",label:"Matériel",value:x=>x.name},{key:"category",label:"Catégorie",value:x=>x.category},{key:"quantity",label:"Quantité",value:x=>x.quantity},{key:"state",label:"État",value:x=>x.state},{key:"location",label:"Rangement",value:x=>x.location}]),simple("materiel-besoins","Matériel COM — Besoins","Besoins, priorité, horizon, budget et avancement.",material.data?.needs??[],[{key:"title",label:"Besoin",value:x=>x.title},{key:"priority",label:"Priorité",value:x=>x.priority},{key:"horizon",label:"Horizon",value:x=>x.horizon},{key:"estimated_budget",label:"Budget",value:x=>x.estimated_budget},{key:"status",label:"Statut",value:x=>x.status}]),simple("materiel-demandes","Matériel COM — Demandes & devis","Dossiers de financement et demandes regroupées.",material.data?.requests??[],[{key:"title",label:"Dossier",value:x=>x.title},{key:"status",label:"Statut",value:x=>x.status},{key:"sent_at",label:"Transmis le",value:x=>x.sent_at}]),simple("journal","Journal d’activité","Actions tracées et audit de l’application.",audit.data??[],[{key:"occurred_at",label:"Date",value:x=>formatDateTime(x.occurred_at)},{key:"action",label:"Action",value:x=>x.action},{key:"actor_name",label:"Auteur",value:x=>x.actor_name},{key:"detail",label:"Détail",value:x=>x.detail}])];
return <AppShell title="Exports" subtitle="Fichiers Excel mis en forme — en-têtes, bordures et colonnes ajustées">{preview?<Card className="mb-5 border-violet-200 bg-violet-50"><CardContent className="flex gap-3 p-4"><Eye className="mt-0.5 size-5 text-icc-violet"/><div><b>Mode consultation</b><p className="text-sm text-muted-foreground">Le catalogue reste visible, mais les données et téléchargements sont réservés aux profils habilités.</p></div></CardContent></Card>:null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{blocks.map(block=><Card key={block.name}><CardHeader><CardTitle className="text-base">{block.label}</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{block.description}</p><p className="text-xs text-muted-foreground">{preview?"0 ligne affichée en consultation":`${block.count} ligne(s) disponibles`}</p><Button className="w-full gap-2" onClick={block.go} disabled={preview||block.count===0}><Download className="size-4"/>Exporter en Excel</Button>{preview?<p className="text-center text-[11px] font-semibold text-icc-violet">Action réservée aux profils habilités</p>:null}</CardContent></Card>)}</div></AppShell>}
