import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { IccHeader } from "@/components/IccHeader";
import { HomeHero } from "@/components/home/HomeHero";
import { HomeMenuGrid } from "@/components/home/HomeMenuGrid";
import { HomeDashboard } from "@/components/home/HomeDashboard";
import { OrganizationDashboard } from "@/components/home/OrganizationDashboard";
import { TeamLifePanel } from "@/components/home/TeamLifePanel";
import { PERIOD_LABELS, type DashboardPeriod } from "@/lib/period";
export const Route=createFileRoute("/_authenticated/tableau-de-bord")({head:()=>({meta:[{title:"Accueil — COM ICC Le Mans"},{name:"description",content:"Accueil du pôle Communication ICC Le Mans : versets, accès aux modules, tableaux de bord et vie d’équipe."},{property:"og:title",content:"Accueil — COM ICC Le Mans"},{property:"og:type",content:"website"}]}),component:Home});
function Home(){const[period,setPeriod]=useState<DashboardPeriod>(()=>{if(typeof window==="undefined")return"month";const saved=window.localStorage.getItem("icc-dashboard-period") as DashboardPeriod|null;return saved&&Object.keys(PERIOD_LABELS).includes(saved)?saved:"month"});const change=(value:DashboardPeriod)=>{setPeriod(value);if(typeof window!=="undefined")window.localStorage.setItem("icc-dashboard-period",value)};return <div className="min-h-screen bg-background text-foreground"><IccHeader/><main className="mx-auto max-w-7xl px-4 py-6"><HomeHero/><HomeMenuGrid/><section className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-card p-4"><div><p className="font-black text-icc-violet">Période du tableau de bord</p><p className="text-xs text-muted-foreground">Les chiffres liés à des dates sont calculés uniquement sur la période choisie.</p></div><select aria-label="Période du tableau de bord" className="h-10 rounded-md border border-input bg-background px-3 text-sm font-semibold" value={period} onChange={e=>change(e.target.value as DashboardPeriod)}>{Object.entries(PERIOD_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></section><HomeDashboard period={period}/><OrganizationDashboard period={period}/><TeamLifePanel/></main></div>}
