import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Plus,Trash2,CheckCircle2,RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { AppShell,EmptyState } from "@/components/AppShell";
import { Field } from "@/components/admin/form-kit";
import { useCurrentRole } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { formatDate,logAction,membersQuery,polesQuery,programsQuery,TASK_PRIORITY_LABEL,tasksQuery,type Task } from "@/lib/icc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Dialog,DialogContent,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/_authenticated/taches")({head:()=>({meta:[{title:"Tâches — COM ICC Le Mans"}]}),component:Taches});
type Draft={id:string|null;title:string;detail:string;due_date:string;priority:string;assignee_member_id:string;pole_id:string;program_id:string};
const EMPTY:Draft={id:null,title:"",detail:"",due_date:"",priority:"normale",assignee_member_id:"",pole_id:"",program_id:""};
const selectClass="h-10 w-full rounded-md border border-input bg-background px-3 text-sm";
function Taches(){
 const tasks=useQuery(tasksQuery),members=useQuery(membersQuery),poles=useQuery(polesQuery),programs=useQuery(programsQuery),qc=useQueryClient(),{member,isStaff}=useCurrentRole(),[draft,setDraft]=useState<Draft|null>(null);
 const memberName=new Map((members.data?.members??[]).map(m=>[m.id,m.full_name])),poleName=new Map((poles.data??[]).map(p=>[p.id,p.name])),programMap=new Map((programs.data??[]).map(p=>[p.id,p]));const refresh=()=>qc.invalidateQueries({queryKey:["tasks"]});
 const save=useMutation({mutationFn:async(v:Draft)=>{const title=v.title.trim();if(!title)throw new Error("Le titre est obligatoire.");const payload={title,detail:v.detail.trim()||null,due_date:v.due_date||null,priority:v.priority,status:"todo",assignee_member_id:v.assignee_member_id||null,pole_id:v.pole_id||null,program_id:v.program_id||null};const q=v.id?supabase.from("tasks").update(payload).eq("id",v.id):supabase.from("tasks").insert(payload);const{error}=await q;if(error)throw error;await logAction({action:v.id?"tache_modifiee":"tache_creee",entity:"task",entityId:v.id??title,detail:title,actorName:member?.full_name})},onSuccess:()=>{toast.success("Tâche enregistrée");setDraft(null);refresh()},onError:(e:Error)=>toast.error(e.message)});
 const status=useMutation({mutationFn:async({task,done}:{task:Task;done:boolean})=>{const{error}=await supabase.from("tasks").update({status:done?"done":"todo"}).eq("id",task.id);if(error)throw error;await logAction({action:"tache_statut",entity:"task",entityId:task.id,detail:`${task.title} → ${done?"Terminée":"À faire"}`,actorName:member?.full_name})},onSuccess:refresh});
 const remove=useMutation({mutationFn:async(task:Task)=>{const{error}=await supabase.from("tasks").delete().eq("id",task.id);if(error)throw error},onSuccess:refresh});
 const today=new Date().toISOString().slice(0,10);
 const renderTask=(task:Task)=>{const isDone=task.status==="done",late=!isDone&&!!task.due_date&&task.due_date<today;return <div key={task.id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-2"><p className={`font-medium ${isDone?"line-through opacity-70":""}`}>{task.title}</p><Badge variant={task.priority==="haute"?"destructive":"outline"}>{TASK_PRIORITY_LABEL[task.priority]??task.priority}</Badge></div>{task.detail?<p className="mt-1 text-sm text-muted-foreground">{task.detail}</p>:null}<div className="mt-2 flex flex-wrap gap-2 text-xs text-muted-foreground"><span className={late?"font-semibold text-destructive":""}>{task.due_date?formatDate(task.due_date):"Sans échéance"}</span>{task.assignee_member_id?<span>· {memberName.get(task.assignee_member_id)??task.assignee_member_id}</span>:null}{task.pole_id?<span>· {poleName.get(task.pole_id)??task.pole_id}</span>:null}</div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant={isDone?"outline":"default"} onClick={()=>status.mutate({task,done:!isDone})}>{isDone?<><RotateCcw className="mr-1 size-4"/>Remettre à faire</>:<><CheckCircle2 className="mr-1 size-4"/>Marquer terminée</>}</Button>{isStaff?<><Button variant="ghost" size="sm" onClick={()=>setDraft({id:task.id,title:task.title,detail:task.detail??"",due_date:task.due_date??"",priority:task.priority,assignee_member_id:task.assignee_member_id??"",pole_id:task.pole_id??"",program_id:task.program_id??""})}>Modifier</Button><Button variant="ghost" size="sm" className="text-destructive" onClick={()=>remove.mutate(task)}><Trash2 className="size-4"/></Button></>:null}</div></div>};
 const allTasks=tasks.data??[];const groupIds=Array.from(new Set(allTasks.map(t=>t.program_id??"__none__"))).sort((a,b)=>{if(a==="__none__")return 1;if(b==="__none__")return-1;return (programMap.get(a)?.start_date??"").localeCompare(programMap.get(b)?.start_date??"")});
 return <AppShell title="Tâches" subtitle="Les tâches sont regroupées par programme pour garder une vue lisible"><div className="mb-5 flex justify-end">{isStaff?<Button onClick={()=>setDraft(EMPTY)}><Plus className="mr-2 size-4"/>Nouvelle tâche</Button>:null}</div>{tasks.isLoading?<Skeleton className="h-48"/>:allTasks.length===0?<EmptyState title="Aucune tâche"/>:<div className="space-y-4">{groupIds.map(groupId=>{const list=allTasks.filter(t=>(t.program_id??"__none__")===groupId),todo=list.filter(t=>t.status!=="done"),done=list.filter(t=>t.status==="done"),program=groupId==="__none__"?null:programMap.get(groupId);return <Card key={groupId}><CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">{program?program.title:"Sans programme"}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{program?formatDate(program.start_date):"Tâches générales non rattachées à un programme"}</p></div><div className="flex gap-2"><Badge variant={todo.length?"default":"outline"}>{todo.length} à faire</Badge><Badge variant="outline">{done.length} terminée{done.length>1?"s":""}</Badge>{program?<Button asChild size="sm" variant="ghost"><Link to="/programme/$id" params={{id:program.id}}>Ouvrir le programme</Link></Button>:null}</div></div></CardHeader><CardContent><div className="grid gap-4 lg:grid-cols-2"><div className="space-y-3"><p className="text-xs font-black uppercase tracking-wide text-muted-foreground">À faire</p>{todo.length?todo.map(renderTask):<p className="rounded-lg bg-muted/30 p-3 text-xs text-muted-foreground">Aucune tâche à faire.</p>}</div><details className="space-y-3" open={done.length>0&&todo.length===0}><summary className="cursor-pointer text-xs font-black uppercase tracking-wide text-muted-foreground">Terminées ({done.length})</summary><div className="mt-3 space-y-3">{done.length?done.map(renderTask):<p className="rounded-lg bg-muted/30 p-3 text-xs text-muted-foreground">Aucune tâche terminée.</p>}</div></details></div></CardContent></Card>})}</div>}
 <Dialog open={!!draft} onOpenChange={o=>{if(!o)setDraft(null)}}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{draft?.id?"Modifier la tâche":"Nouvelle tâche"}</DialogTitle></DialogHeader>{draft?<div className="space-y-4"><Field label="Titre"><Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label="Détail"><Textarea value={draft.detail} onChange={e=>setDraft({...draft,detail:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Échéance"><Input type="date" value={draft.due_date} onChange={e=>setDraft({...draft,due_date:e.target.value})}/></Field><Field label="Priorité"><select className={selectClass} value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}>{Object.entries(TASK_PRIORITY_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Assignée à"><select className={selectClass} value={draft.assignee_member_id} onChange={e=>setDraft({...draft,assignee_member_id:e.target.value})}><option value="">Non assignée</option>{(members.data?.members??[]).map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></Field><Field label="Pôle"><select className={selectClass} value={draft.pole_id} onChange={e=>setDraft({...draft,pole_id:e.target.value})}><option value="">Aucun</option>{(poles.data??[]).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Programme lié"><select className={selectClass} value={draft.program_id} onChange={e=>setDraft({...draft,program_id:e.target.value})}><option value="">Aucun</option>{(programs.data??[]).map(p=><option key={p.id} value={p.id}>{p.title} — {formatDate(p.start_date)}</option>)}</select></Field></div><p className="text-xs text-muted-foreground">Une tâche liée à un programme apparaîtra automatiquement dans le groupe de ce programme.</p></div>:null}<DialogFooter><Button variant="ghost" onClick={()=>setDraft(null)}>Annuler</Button><Button disabled={save.isPending} onClick={()=>draft&&save.mutate(draft)}>Enregistrer</Button></DialogFooter></DialogContent></Dialog></AppShell>}
