import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useCurrentRole } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";

type Assignment = { id:string; pole_id:string; required_count?:number|null; memberIds:string[] };
type Props = { programId:string; programTitle:string; assignments:Assignment[]; members:any[]; poles:any[] };
const stamp=(v:string)=>new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));

export function ProgramParticipationPanel({programId,programTitle,assignments,members,poles}:Props){
 const {member,isStaff}=useCurrentRole(); const qc=useQueryClient(); const [note,setNote]=useState<Record<string,string>>({}); const [direct,setDirect]=useState<Record<string,string>>({});
 const proposals=useQuery({queryKey:["program-proposals",programId],queryFn:async()=>{const {data,error}=await (supabase as any).from("program_proposals").select("*").eq("program_id",programId).order("created_at",{ascending:true}); if(error) throw error; return data??[];}});
 const memberships=useQuery({queryKey:["my-program-poles",member?.id],enabled:!!member?.id,queryFn:async()=>{const {data,error}=await (supabase as any).from("member_poles").select("pole_id").eq("member_id",member!.id);if(error)throw error;return new Set((data??[]).map((x:any)=>x.pole_id));}});
 const modes=useQuery({queryKey:["program-assignment-modes",programId],queryFn:async()=>{const ids=assignments.map(a=>a.id);if(!ids.length)return[];const {data,error}=await (supabase as any).from("program_assignment_members").select("assignment_id,member_id,assignment_mode,assigned_at").in("assignment_id",ids);if(error)throw error;return data??[];}});
 const names=useMemo(()=>new Map(members.map(m=>[m.id,m.full_name])),[members]); const poleNames=useMemo(()=>new Map(poles.map(p=>[p.id,p.name])),[poles]);
 const refresh=()=>{qc.invalidateQueries({queryKey:["program-proposals",programId]});qc.invalidateQueries({queryKey:["program-assignment-modes",programId]});qc.invalidateQueries({queryKey:["programs"]});};
 const propose=useMutation({mutationFn:async(aid:string)=>{const {error}=await (supabase as any).rpc("propose_for_program",{p_assignment_id:aid,p_note:note[aid]?.trim()||null});if(error)throw error;},onSuccess:()=>{refresh();toast.success("Proposition envoyée");},onError:(e:any)=>toast.error(e.message)});
 const decide=useMutation({mutationFn:async({id,d}:{id:string,d:string})=>{const {error}=await (supabase as any).rpc("decide_program_proposal",{p_proposal_id:id,p_decision:d});if(error)throw error;},onSuccess:()=>{refresh();toast.success("Proposition traitée");},onError:(e:any)=>toast.error(e.message)});
 const assign=useMutation({mutationFn:async({aid,mid}:{aid:string,mid:string})=>{const {error}=await (supabase as any).rpc("direct_assign_program_member",{p_assignment_id:aid,p_member_id:mid,p_source:"direct"});if(error)throw error;},onSuccess:()=>{refresh();toast.success("Affectation directe confirmée");},onError:(e:any)=>toast.error(e.message)});
 const withdraw=useMutation({mutationFn:async(id:string)=>{const {error}=await (supabase as any).rpc("withdraw_program_proposal",{p_proposal_id:id});if(error)throw error;},onSuccess:refresh});
 return <div className="mt-4 space-y-3 rounded-xl border bg-muted/10 p-4"><div><h3 className="font-black text-icc-violet">Participation & besoins</h3><p className="text-xs text-muted-foreground">Transparence : affectations, attentes et propositions sont visibles par l’équipe. Les notes de proposition restent réservées aux responsables.</p></div>
 {assignments.map(a=>{const required=a.required_count||0;const confirmed=(modes.data??[]).filter((x:any)=>x.assignment_id===a.id&&["direct","proposal"].includes(x.assignment_mode));const solicited=(modes.data??[]).filter((x:any)=>x.assignment_id===a.id&&x.assignment_mode==="solicited");const pending=(proposals.data??[]).filter((p:any)=>p.assignment_id===a.id&&p.status==="pending");const covered=required>0&&confirmed.length>=required;const mine=pending.find((p:any)=>p.member_id===member?.id);const myPole=!!memberships.data?.has(a.pole_id);const candidates=members.filter(m=>m.status==="active"&&!m.deleted&&!a.memberIds.includes(m.id));return <div key={a.id} className="rounded-lg border bg-background p-3"><div className="flex flex-wrap items-center justify-between gap-2"><b>{poleNames.get(a.pole_id)??"Pôle"}</b>{required>0?<Badge variant={covered?"secondary":"destructive"}>{confirmed.length}/{required} confirmé{confirmed.length>1?"s":""}</Badge>:null}</div>
 <div className="mt-2 space-y-1 text-sm">{confirmed.map((x:any)=><div key={x.member_id}>✓ <b>{names.get(x.member_id)??x.member_id}</b> · {x.assignment_mode==="direct"?"Affecté directement":"Proposition acceptée"}</div>)}{solicited.map((x:any)=><div key={x.member_id}>⏳ <b>{names.get(x.member_id)??x.member_id}</b> · En attente de réponse</div>)}{pending.map((p:any)=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md bg-muted/30 px-2 py-1.5"><span>🙋 <b>{names.get(p.member_id)??p.member_id}</b> · proposition {stamp(p.created_at)}</span>{isStaff?<span className="flex items-center gap-1">{p.note?<span className="mr-2 text-xs text-muted-foreground">Note : {p.note}</span>:null}<Button size="sm" onClick={()=>decide.mutate({id:p.id,d:"assigned"})}>Affecter</Button><Button size="sm" variant="outline" onClick={()=>decide.mutate({id:p.id,d:"refused"})}>Refuser</Button></span>:null}</div>)}</div>
 {myPole&&!covered&&!a.memberIds.includes(member?.id??"")&&!mine?<div className="mt-3 flex flex-col gap-2 sm:flex-row"><Textarea className="min-h-9" placeholder="Note facultative (visible uniquement par le Référent/Direction)" value={note[a.id]??""} onChange={e=>setNote(v=>({...v,[a.id]:e.target.value}))}/><Button onClick={()=>propose.mutate(a.id)}>🙋 Je me propose</Button></div>:null}{mine?<div className="mt-2"><Button size="sm" variant="outline" onClick={()=>withdraw.mutate(mine.id)}>Retirer ma proposition</Button></div>:null}
 {isStaff?<div className="mt-3 flex flex-wrap items-center gap-2 border-t pt-3"><span className="text-xs font-bold">Affecter directement :</span><select className="h-9 min-w-48 rounded-md border bg-background px-2 text-sm" value={direct[a.id]??""} onChange={e=>setDirect(v=>({...v,[a.id]:e.target.value}))}><option value="">Choisir un membre…</option>{candidates.map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select><Button size="sm" disabled={!direct[a.id]} onClick={()=>assign.mutate({aid:a.id,mid:direct[a.id]})}>Affecter sans réponse</Button></div>:null}</div>})}
 </div>;
}
